### PR TITLE
Remove inversion of axes

### PR DESCRIPTION
**Pull request by TiagoCavalcante**
The camera position calculus are based on [spherical polar coordinates](https://en.wikipedia.org/wiki/Spherical_coordinate_system).

### CODE REVIEW

**Comment by TiagoCavalcante** [comment]
About the 1st commit: that changed the reference image because of a few pixels of difference. Floating-point modulus isn't so accurate (and the threshold is low).

**Comment by TiagoCavalcante** [comment]
Seems that the polar coordinates invert the axes (https://en.wikipedia.org/wiki/Spherical_coordinate_system#Conventions). But I'm not sure though.

**Comment by TiagoCavalcante** [comment]
I'm struggling with getting the pan working again, so I created an [question](https://discourse.threejs.org/t/move-camera-with-mouse/30005).

**Comment by makc** [comment]
> Files changed: 42

is this PR an answer to life, universe and everything?

**Comment by TiagoCavalcante** [comment]
@makc that was just a coincidence.

**Comment by makc** [comment]
kek

**Pull request closed without merging**
