### PR TITLE
Add text primitive

### PR DESCRIPTION
**Pull request by TiagoCavalcante**
The documentation needs to be updated before this be merged.

### CODE REVIEW

**Comment by TiagoCavalcante** [comment]
@rocky the way [WL's Text](https://reference.wolfram.com/language/ref/Text.html) coordinates work is different, but I didn't want to follow that because it'd "break" the coordinate "pattern" (all primitives but text would use coords for the coordinates).

What do you think about it? Should I change it to be closer to WL's Text?

**Comment by rocky** [comment]
> @rocky the way [WL's Text](https://reference.wolfram.com/language/ref/Text.html) coordinates work is different, but I didn't want to follow that because it'd "break" the coordinate "pattern" (all primitives but text would use coords for the coordinates).
> 
> What do you think about it? Should I change it to be closer to WL's Text?

The short answer is closer to WL's text, but there are big "but"s....

Let's back up a little... There are in theory two forms of graphics3D - what is here now which I think we've been calling the "compact form" protocol, and a form that looks more like a WL M-Expression which we have been calling the "long form" protocol. 

Right now we don't support the "long form" but should eventually.  And that part could just be a translator in javascript that converts long form to compact form. It could even be a separate project.

For the "long form" protocol I hope the answer is clear - follow WL, because that's what everyone (Mathics and Symja) is trying to do and that is what makes the most sense. 

For the "compact form" protocol, there _is_ some leeway. 

But the way I think about this is similar to a question that came up a long time ago when I worked at IBM Research and people were trying decide what kinds of things should be done in hardware, i.e. chip design, and what things should be done in software, i.e. a compiler. 

The overall principle was - in which place is it easier or more natural to do. 

Although in theory the translation could be done in Mathics (and also Symja should it choose), I don't see that it is all that hard to do here in mathics threejs. I believe it might be as simple as  a function call that would make the translation. 

For 2D there is Offset, which works I guess like what you describe. But I don't see that for 3D. 

As for breaking a pattern, right now I believe that were mathic-threejs-backend were to support more of Graphics3D, you'd find a _lot_ more patterns broken. See for example [Inset](https://reference.wolfram.com/language/ref/Inset.html).

Given this, there may be an advantage of having in place some layer to handle such kinds of translations.

These are my thoughts from a coding design perspective and how I would think about this and handle it. 

Maybe it would be good to get opinions of others. @mmatera ? @axkr ?

**Comment by mmatera** [comment]
Usually, this change it the semantics of WL have a motivation, which quite often is not evident. However, if we do not have a strong argument to follow the same semantics, I think it is fine to have a different, but more consistent semantics at the level of this API.

**Comment by rocky** [comment]
The reason to follow the same semantics is so that for a given input we get the same output. To use an example, there are a number of places where in Mathics-core we change sympy's semantics for WL's.

**Comment by mmatera** [comment]
In the core, it is more involved because we want to make the interpreter compatible with the existing third-party WL code. Here we always need some translation layer.

**Pull request merged**
